class AddTimestampsToArticles < ActiveRecord::Migration[6.1]
  def change
    # add_column :articles, :created_at, :datetime
    # add_column :articles, :updated_at, :datetime
    # this will not work now because the timestamp is autogenerated when it is created but if not, use "t.timestamps" to get the timestamp 
  end
end
